# Generated by Django 5.1.2 on 2024-10-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('both', 'Both')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='online_books/')),
            ],
        ),
    ]
