# Generated by Django 5.1.2 on 2024-10-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_onlinebooks_onlinebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
